---
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    file_names: false
    prefer_relative_imports: true
    always_use_package_imports: false
    public_member_api_docs: false

analyzer:
  exclude:
    - ./firebase_options.dart
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.config.dart"
    - "**/generated_plugin_registrant.dart"
  strong-mode:
    # Will become the default once non-nullable types land
    # https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629
    implicit-casts: true
    implicit-dynamic: true
