---
name: hizonchristian
description: Portfolio of Christian Hizon. He worked on several development projects, taught students, and collaborated with talented people to create applications for both business and consumer use. I'm quietly confident, naturally curious and perpetually working on improving my skills as a developer
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.1.0
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.5
  very_good_analysis: ^3.0.1
dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen: ^4.3.0
  flutter_gen_runner: ^4.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  lint: ^1.10.0

flutter_gen:
  output: lib/core/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
